jwt:
   token:
     signing-key: |
       -----BEGIN RSA PRIVATE KEY-----
       MIIEowIBAAKCAQEAq9+mKq04Z4CmyYOHxwQUiY3ZnasssOzYvBL+a9jgjHOsfZWU
       GImILqjj5SkqQYtuKl6d8TJEQZz9JJsXgZLf7ur+/vngkWnEk2nmQx89LBj6vixw
       9kWE6E7V7TEgFb7D0lBT626x6O6GjvwZS6F1UuxLdMo9uIgE3zF55yab9nbpnwch
       G0CChF+97NZJ+HyyPC7Vyne71WKtqTVXDG79Hoi/THiIiR7bgvTBAiKhNdMWVljm
       tU4xKmu6VraV3aaz79OULtMNl/GiRDKLKduP3sF/Kun2w01C+Ns2jfpnnwNlg829
       +hN5U1QPQ9FZlPIKU2d5/xQyQ4271Ft3qgGuGQIDAQABAoIBAAhHhMSnhYEO5Hnu
       mRrQKoEZ0TLULRn0vtgIfjMJxn9djyCZlQG9lk7RGfFPE1cG9W6bEjatOjaC7nrV
       8cLvJVRoA5KazOOUWcDUKCBxn8vBBEsm7uYeITHjolCDvkzt3JcEAZbkxTM4UkkP
       AdTv2Sv+cAAXQfPisYFi68Fjzb2Ilq/XMzieA0Fk2vw3cssqCXdw7AeyvXHcZTpb
       e2v/8Ed3FzXMaYpLWuI+WwNDouPJNR58BpX/A17gljoRbXng17WcbEU9zT5526ah
       gGrbtbhym7c/d8IwMiHkwWxiS8ZqeFq/msVcin0Btsmqbp3+bjTyOme15yJbykLl
       EO7HxIECgYEA1gFJPHI7sWVn6oVopSWUbkOQhDSBz2tcmblCT7FShxoMrCuERgmp
       8trsPTBdAJCRTYUSmHIWxkCUCuPR14oBsDrINtEA5tTUXwpy36t1pUalk5x8N5sI
       cC1ieJ/6cQu/XsURvRln6PBExj12K5ppIUmE2/KmffwRdzBU5GTpSMkCgYEAzZnb
       z233comXiqkoJjF4t1KtcbpjdskS4gGRvTNt2jYpogSFtQUulvNYnFbeWO2UvzFa
       p0wWdyq3ukL/YLl3o0E81sjvOSWhRCi1H9QEuVwoO4W8uj0c0foGtETJ3Q4tgIYj
       G3pPS9JhHxIYqcSbOGUTZ6RyVsL9t9BGKd2mMtECgYBzUIoYCi3kLxJJqs1yf8d1
       iu6qbmisTdu98bernY8swXqmo2RJIRf0hsbZSeAzV7MUJGqavo9LEK01GQGPtQun
       3GTaNNDZkUFGXSj9ITTpdCHwYlgE1oM7fxkaiom2tG/QLzyZusDlIeLNN30fjbqs
       dyMiKaRRKqx2nxJ/Z2jVEQKBgQCzGrwsiAxOn+P+q/tIwkH52TE06HzrJqCnd1yB
       KIMi25oLBMuBdSEv6I8hql8JsvWoVJM3OAY+C12ACgs0NH0vH46jQOl8q/Y/TQLz
       1hvDaa+2ontU9hXcKWWbtmzvgAFNfAyrTDI1x/BJQ9duVNIvH4X2/H+Ka1TgwrPM
       lsTIcQKBgCmozSMOJi501gE+2rlMrY2QE9namflCZmQi9z/ki7OfJ+BfsxvCvdBH
       OVJfE8qIHbj0RNP974g0Pf+r5gC02RJf7PceYLruhkrQAy3gu7HI4gm3gK2RcspV
       4y6t7wDPNUGYfb7to8kugBFekBfqmiJpElqzA8q4pEPRKb5YRSiB
       -----END RSA PRIVATE KEY-----
      verification-key: |
       -----BEGIN PUBLIC KEY-----
       MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq9+mKq04Z4CmyYOHxwQU
       iY3ZnasssOzYvBL+a9jgjHOsfZWUGImILqjj5SkqQYtuKl6d8TJEQZz9JJsXgZLf
       7ur+/vngkWnEk2nmQx89LBj6vixw9kWE6E7V7TEgFb7D0lBT626x6O6GjvwZS6F1
       UuxLdMo9uIgE3zF55yab9nbpnwchG0CChF+97NZJ+HyyPC7Vyne71WKtqTVXDG79
       Hoi/THiIiR7bgvTBAiKhNdMWVljmtU4xKmu6VraV3aaz79OULtMNl/GiRDKLKduP
       3sF/Kun2w01C+Ns2jfpnnwNlg829+hN5U1QPQ9FZlPIKU2d5/xQyQ4271Ft3qgGu
       GQIDAQAB
       -----END PUBLIC KEY-----
